### ISSUE TITLE
Error when rendering genders on empty database

### ISSUE THREAD

**Issue by busla** [vthorsteinsson/Reynir#40]
No checks for empty dicts are made in templates/genders.html:
https://github.com/vthorsteinsson/Reynir/blob/master/templates/genders.html#L26
https://github.com/vthorsteinsson/Reynir/blob/master/templates/genders.html#L41

Calculating empty vars results in:

```python
Traceback (most recent call last):
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/levy/Code/Reynir/main.py", line 135, in decorated_function
    resp = f(*args, **kwargs)
  File "/Users/levy/Code/Reynir/main.py", line 754, in genders
    return render_template("genders.html", result = result, total = total)
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/levy/Code/Reynir/venv/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/levy/Code/Reynir/venv/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/levy/Code/Reynir/venv/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/levy/Code/Reynir/venv/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/levy/Code/Reynir/templates/genders.html", line 2, in top-level template code
    {% extends "container-normal.html" %}
  File "/Users/levy/Code/Reynir/templates/container-normal.html", line 2, in top-level template code
    {% extends "container.html" %}
  File "/Users/levy/Code/Reynir/templates/container.html", line 83, in top-level template code
    {% block container %}
  File "/Users/levy/Code/Reynir/templates/container-normal.html", line 9, in block "container"
    {% block content %}
  File "/Users/levy/Code/Reynir/templates/genders.html", line 45, in block "content"
    <td class="count female">{{ (total.kvk / (total.kvk + total.kk) * 100) | format_is(1) }}%</td>
  File "/Users/levy/code/pypy3/lib_pypy/_decimal.py", line 665, in method
    self, other, strict=False)
  File "/Users/levy/code/pypy3/lib_pypy/_decimal.py", line 1335, in method
    mpd_func(res._mpd, a._mpd, b._mpd, ctx, status_ptr)
  File "/Users/levy/code/pypy3/lib_pypy/_decimal.py", line 1621, in __exit__
    self.context._add_status(status)
  File "/Users/levy/code/pypy3/lib_pypy/_decimal.py", line 1253, in _add_status
    raise exception
decimal.InvalidOperation
```

**Comment by busla** [comment]
Fixed here:
https://github.com/busla/Reynir/commit/241267d6a49bf27016a64aaed42029b68c7cce27

**Comment by vthorsteinsson** [comment]
Should be fixed in latest commit to Reynir/master. https://github.com/vthorsteinsson/Reynir/commit/29446da47d1aeeca18350ee78a4bbbb4127720b0#diff-dc478e19aab1c8e3131dfa7eebc42c16
