### ISSUE TITLE
Error on POST

### ISSUE THREAD

**Issue by busla** [vthorsteinsson/Reynir#44]
Get this error when POST´ing.

Running Greynir on Docker.

```python
172.18.0.1 - - [02/Dec/2016 15:58:53] "POST /query.api HTTP/1.1" 500 -
greynir_web | Traceback (most recent call last):
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1994, in __call__
greynir_web |     return self.wsgi_app(environ, start_response)
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1985, in wsgi_app
greynir_web |     response = self.handle_exception(e)
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1540, in handle_exception
greynir_web |     reraise(exc_type, exc_value, tb)
greynir_web |   File "/usr/local/site-packages/flask/_compat.py", line 33, in reraise
greynir_web |     raise value
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1982, in wsgi_app
greynir_web |     response = self.full_dispatch_request()
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1614, in full_dispatch_request
greynir_web |     rv = self.handle_user_exception(e)
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1517, in handle_user_exception
greynir_web |     reraise(exc_type, exc_value, tb)
greynir_web |   File "/usr/local/site-packages/flask/_compat.py", line 33, in reraise
greynir_web |     raise value
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1612, in full_dispatch_request
greynir_web |     rv = self.dispatch_request()
greynir_web |   File "/usr/local/site-packages/flask/app.py", line 1598, in dispatch_request
greynir_web |     return self.view_functions[rule.endpoint](**req.view_args)
greynir_web |   File "/usr/src/app/Reynir/main.py", line 471, in query
greynir_web |     auto_uppercase = q.islower() if auto_uppercase else False))
greynir_web |   File "/usr/src/app/Reynir/tokenizer.py", line 1590, in disambiguate_phrases
greynir_web |     token = next(token_stream)
greynir_web |   File "/usr/src/app/Reynir/tokenizer.py", line 1735, in recognize_entities
greynir_web |     token = next(token_stream)
greynir_web |   File "/usr/src/app/Reynir/tokenizer.py", line 1179, in parse_phrases_2
greynir_web |     next_token = next(token_stream)
greynir_web |   File "/usr/src/app/Reynir/tokenizer.py", line 1001, in parse_phrases_1
greynir_web |     next_token = next(token_stream)
greynir_web |   File "/usr/src/app/Reynir/tokenizer.py", line 741, in annotate
greynir_web |     w, m = db.lookup_word(t.txt, at_sentence_start, auto_uppercase)
greynir_web |   File "/usr/src/app/Reynir/bindb.py", line 272, in lookup_word
greynir_web |     return self._lookup(w, at_sentence_start, auto_uppercase, self._meanings_func)
greynir_web |   File "/usr/src/app/Reynir/bindb.py", line 425, in _lookup
greynir_web |     cw = Wordbase.dawg().slice_compound_word(w)
greynir_web |   File "/usr/src/app/Reynir/dawgdictionary.py", line 252, in dawg
greynir_web |     Wordbase._dawg = Wordbase._load()
greynir_web |   File "/usr/src/app/Reynir/dawgdictionary.py", line 246, in _load
greynir_web |     return Wordbase._load_resource("ordalisti") # Main dictionary
greynir_web |   File "/usr/src/app/Reynir/dawgdictionary.py", line 229, in _load_resource
greynir_web |     dawg.load(pname)
greynir_web |   File "/usr/src/app/Reynir/dawgdictionary.py", line 102, in load
greynir_web |     with codecs.open(fname, mode='r', encoding='utf-8') as fin:
greynir_web |   File "/usr/local/lib-python/3/codecs.py", line 896, in open
greynir_web |     file = builtins.open(filename, mode, buffering)
greynir_web | FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/Reynir/resources/ordalisti.text.dawg'
```

**Comment by vthorsteinsson** [comment]
Fixed in Dockerfile - now runs dawgbuilder.py to generate the ordalisti.text.dawg file before starting
